### ISSUE TITLE
Correción del link del dia 2

### ISSUE THREAD

**Issue by panchocorderos** [brolag/100DaysOfReact#1]
En la recomendación de enlaces del día 2 esta _'What The fork is a Closure por Dan Abramov'_ con el siguiente enlace [https://whatthefork.is/closure](https://whatthefork.is/closure) y se actualizó por éste [https://whatthefuck.is/closure](https://whatthefuck.is/closure)

Saludos! Gracias por este repo! 😁

**Comment by brolag** [comment]
Muchas gracias @panchocorderos !
